name: Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SQRL_VERSION: [0.5.6, 0.5.7]

    env:
      DOCKER_REPO: datasqrl/flink-jar-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull base images
        run: |
          docker pull gradle:8.6-jdk11
          docker pull flink:1.19.1-scala_2.12-java11

      - name: Build and push Docker image
        working-directory: flink-dockerfile-example
        run: |
          docker build --build-arg SQRL_VERSION=${{ matrix.SQRL_VERSION }} -t $DOCKER_REPO:${{ matrix.SQRL_VERSION }} .
          docker push $DOCKER_REPO:${{ matrix.SQRL_VERSION }}
