name: Build uber jar

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  uber-jar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SQRL_VERSION: [0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, dev]

    env:
      DOCKER_REPO: datasqrl/flink-jar-runner
      VERSION: ${{ github.event_name == 'release' && github.event.action == 'created' && github.ref_name || '1.0.0-SNAPSHOT' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull base images
        run: |
          docker pull maven:3.9.9-eclipse-temurin-11
          docker pull alpine:3

      - name: Run Maven Build
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          mvn -B versions:set -DnewVersion=${{ env.VERSION }}
          mvn -B clean install -DskipTests=true

      - name: Build Docker image
        run: |
          cp uber-jar/Dockerfile .
          DOCKER_TAG=$DOCKER_REPO:jar-only-${{ env.VERSION }}-sqrlv${{ matrix.SQRL_VERSION }}
          docker build --build-arg SQRL_VERSION=${{ matrix.SQRL_VERSION }} --build-arg GITHUB_ACTOR=${{ github.actor }} --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --build-arg RUNNER_VERSION=${{ env.VERSION }} -t $DOCKER_TAG .

      - name: Push Docker image
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          DOCKER_TAG=$DOCKER_REPO:${{ env.VERSION }}-sqrlv${{ matrix.SQRL_VERSION }}
          docker push $DOCKER_TAG

